services:
  - type: web
    name: jz-home-yard-services
    runtime: static
    staticPublishPath: ./
    buildCommand: ""
    routes:
      - type: rewrite
        source: /thanks
        destination: /thanks.html
